#!/opt/alt/python27/bin/python2.7
# Binh Pham
# Shows cPanel owner of a domain

import sys
import subprocess

try:
    domain_input = sys.argv
    domain = domain_input[1]

    cmd = 'grep "={}" /var/cpanel/users/*'.format(domain)
    cmd_result = subprocess.check_output(cmd, shell=True)

    print((cmd_result.split(":")[0]).split("/")[4])
except:
    print("Oops! There was an error. Please check usage is correct.")
    print("Usage: whoowns domain.com")

